"""tabla espirales

Revision ID: 37c3bfe77380
Revises: d9348a57a2af
Create Date: 2026-05-15 09:29:17.566691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c3bfe77380'
down_revision = 'd9348a57a2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espirales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=10), nullable=False))
        batch_op.drop_column('numero_espiral')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espirales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_espiral', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
