"""agregar stock espiral

Revision ID: 60b33afb28f2
Revises: 3fb6f3ec3afb
Create Date: 2026-05-15 10:27:14.207374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b33afb28f2'
down_revision = '3fb6f3ec3afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espirales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_espiral', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))
        batch_op.drop_column('codigo')
        batch_op.drop_column('stock_actual')
        batch_op.drop_column('capacidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('espirales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('stock_actual', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('codigo', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('stock')
        batch_op.drop_column('numero_espiral')

    # ### end Alembic commands ###
