"""Tablas vending creadas

Revision ID: d9348a57a2af
Revises: 3220715a6ee2
Create Date: 2026-05-14 14:20:13.832579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9348a57a2af'
down_revision = '3220715a6ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_global', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('espirales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('snack_id', sa.Integer(), nullable=False),
    sa.Column('numero_espiral', sa.String(length=10), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['snack_id'], ['snacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espiral_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_agregada', sa.Integer(), nullable=False),
    sa.Column('fecha_reposicion', sa.DateTime(), nullable=True),
    sa.Column('operario', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['espiral_id'], ['espirales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espiral_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['espiral_id'], ['espirales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('inventario_detalle')
    op.drop_table('espirales')
    op.drop_table('snacks')
    op.drop_table('maquinas')
    # ### end Alembic commands ###
